[workspace]
members = [
    "benchmark",
]

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks =false
lto = "fat"
incremental = false
codegen-units = 1
panic = "abort"